# -*- coding: utf-8 -*-
"""book_recommender_streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rz0ZbyfTpO8b21RllYn2uYPxHId3X63q
"""

import streamlit as st
import pickle

# -------------------------------
# Page Setup
# -------------------------------
st.set_page_config(page_title="Book Recommender")
st.title("📚 Book Recommendation System")

# -------------------------------
# Load Data
# -------------------------------
books = pickle.load(open('books.pkl', 'rb'))
similarity = pickle.load(open('similarity.pkl', 'rb'))

# -------------------------------
# Recommendation Function
# -------------------------------
def recommend(book):
    matches = books[books['title'].str.contains(book, case=False)]

    if matches.empty:
        return ["No match found"] * 5, [""] * 5   # ✅ ALWAYS 2 values

    index = matches.index[0]
    distances = similarity[index]

    book_list = sorted(
        list(enumerate(distances)),
        reverse=True,
        key=lambda x: x[1]
    )[1:6]

    names = []
    images = []

    for i in book_list:
        names.append(books.iloc[i[0]].title)
        images.append(books.iloc[i[0]].thumbnail)

    return names, images 

# -------------------------------
# UI Components
# -------------------------------
book_list = books['title'].values
selected_book = st.selectbox("📖 Select a book", book_list)

# -------------------------------
# Button Action
# -------------------------------
if st.button("Recommend"):
    names, images = recommend(selected_book)

    col1, col2, col3, col4, col5 = st.columns(5)

    for i, col in enumerate([col1, col2, col3, col4, col5]):
        with col:
            st.text(names[i])
            st.image(images[i])